### ISSUE TITLE
Bundle Activator MyDominoActivator does not implement BundleActivator.

### ISSUE THREAD

**Issue by frgomes** [frgomes/domino-osgi-sample#1]
Seems like bnd does not like when a class extends BundleActivator indirectly.

```
MyDominoActivator (services.internal)
+-- DominoActivator (domino)
    +-- OsgiContext (domino)
        +-- EmptyBundleActivator (domino)
            +-- BundleActivator (org.osgi.framework)
```

> $ sbt clean package osgiBundle
> [info] Loading global plugins from /home/richard/.sbt/0.13/plugins
> [info] Loading project definition from /home/richard/.sbt/0.13/staging/3effabd4e7aba974f2e8/sbt-osgi/project
> [info] Loading project definition from /home/richard/workspace/domino-osgi-sample/project
> [info] Set current project to root (in build file:/home/richard/workspace/domino-osgi-sample/)
> [success] Total time: 0 s, completed 23-Jul-2015 14:06:40
> [info] Updating {file:/home/richard/workspace/domino-osgi-sample/}root...
> [info] Updating {file:/home/richard/workspace/domino-osgi-sample/}moduleA...
> [info] Updating {file:/home/richard/workspace/domino-osgi-sample/}moduleB...
> [info] Resolving org.fusesource.jansi#jansi;1.4 ...
> [info] Done updating.
> [info] Resolving org.osgi#org.osgi.core;4.3.0 ...
> [info] Packaging /home/richard/workspace/domino-osgi-sample/target/scala-2.10/root_2.10-0.1-SNAPSHOT.jar ...
> [info] Resolving com.github.domino-osgi#domino_2.11;1.1.0 ...
> [info] Done packaging.
> [info] Resolving jline#jline;2.12.1 ...
> [info] Done updating.
> [info] Resolving org.osgi#org.osgi.compendium;4.3.0 ...
> [info] Compiling 1 Scala source to /home/richard/workspace/domino-osgi-sample/moduleA/target/scala-2.11/classes...
> [info] Resolving jline#jline;2.12.1 ...
> [info] Done updating.
> [info] Compiling 1 Scala source to /home/richard/workspace/domino-osgi-sample/moduleB/target/scala-2.11/classes...
> [info] Packaging /home/richard/workspace/domino-osgi-sample/moduleB/target/scala-2.11/moduleb_2.11-0.1-SNAPSHOT.jar ...
> [info] Packaging /home/richard/workspace/domino-osgi-sample/moduleA/target/scala-2.11/modulea_2.11-0.1-SNAPSHOT.jar ...
> [info] Done packaging.
> [info] Done packaging.
> [success] Total time: 2 s, completed 23-Jul-2015 14:06:43
> [error] bnd: The Bundle Activator moduleB.internal.MyDominoActivator does not implement BundleActivator.
> [success] Total time: 0 s, completed 23-Jul-2015 14:06:43

**Comment by frgomes** [comment]
Seems like related to this:
https://groups.google.com/forum/#!topic/bndtools-users/z6u8jQaVGss

**Comment by frgomes** [comment]
https://github.com/bndtools/bnd/issues/1005 is scheduled to be fixed as part of bnd 3.1

**Comment by frgomes** [comment]
I've upgraded http://github.com/frgomes/sbt-osgi so that it now employs bndlib 3.2.0
Then I've made this sample project employ the modified version of sbt-osgi.
Now it fails like this:

<pre>
$ sbt clean package osgiBundle
[info] Loading global plugins from /home/richard/.sbt/0.13/plugins
[info] Loading project definition from /home/richard/.sbt/0.13/staging/32961ba36a0bf2582801/sbt-osgi/project
[info] Loading project definition from /home/richard/workspace/domino-osgi-sample/project
[info] Set current project to root (in build file:/home/richard/workspace/domino-osgi-sample/)
java.lang.NoClassDefFoundError: org/slf4j/LoggerFactory
        at aQute.bnd.osgi.Processor.<init>(Processor.java:97)
        at aQute.bnd.osgi.Analyzer.<init>(Analyzer.java:128)
        at aQute.bnd.osgi.Builder.<init>(Builder.java:74)
        at com.typesafe.sbt.osgi.Osgi$.bundleTask(Osgi.scala:38)
        at com.typesafe.sbt.osgi.SbtOsgi$$anonfun$defaultOsgiSettings$1.apply(SbtOsgi.scala:54)
        at com.typesafe.sbt.osgi.SbtOsgi$$anonfun$defaultOsgiSettings$1.apply(SbtOsgi.scala:54)
        at scala.Function8$$anonfun$tupled$1.apply(Function8.scala:35)
        at scala.Function8$$anonfun$tupled$1.apply(Function8.scala:34)
        at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
        at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
        at sbt.std.Transform$$anon$4.work(System.scala:63)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
        at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
        at sbt.Execute.work(Execute.scala:235)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
        at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
        at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
</pre>

**Comment by lefou** [comment]
Looks like it needs SLF4J which seems to be not provided by current sbt-osgi. In fact this dependency is new since bnd 3.2.0. This is unrelated to the original issue though.
